### ISSUE TITLE
module name can't contain \".\"

### ISSUE THREAD

**Issue by sercruzg** [yangli18/hand_detection#11]
Hi

I wanted to try your code but due to updates in python the modules cannot contain "." in their keys so it cannot be used to load your pretrained weights to train. Is there a way you can change their keys? e.g. features.Conv2d_6.pointwise.0.weight to features_Conv2d_6.pointwise.0.weight

**Comment by yangli18** [comment]
@sercruzg 
Hi, please refer to this [issue](https://github.com/yangli18/hand_detection/issues/5#issuecomment-516231875).
