### ISSUE TITLE
你好，导入出现错误。ModuleNotFoundError: No module named 'layers._ext'

### ISSUE THREAD

**Issue by yangyang117** [yangli18/hand_detection#13]
你好，非常感谢你共享自己的代码。
目前我在运行时出现了一点问题，ModuleNotFoundError: No module named 'layers._ext'。
我看之前issue里面也有关于这个模块的错误，但是没有找到解决方案。._ext文件在 layers文件夹里面好像也没有。
期待你的回答

**Comment by yangli18** [comment]
@yangyang117 你好，可能需要先按照preparation说明编译一下 `sh layers/src/make.sh`。

**Comment by yangyang117** [comment]
谢谢，之前看你的介绍中漏掉了一行，很棒的工作，谢谢你的分享。
