### ISSUE TITLE
xmin, ymin, xmax, ymax, wx, wy, hx, hy, wristx, wristy

### ISSUE THREAD

**Issue by fumingheng** [yangli18/hand_detection#15]
感谢您分享了这份代码，我想问一下xmin, ymin, xmax, ymax, wx, wy, hx, hy, wristx, wristy中wx, wy, hx, hy, wristx, wristy分别代表什么意思，期盼您的答复

**Comment by yangli18** [comment]
@fumingheng You can read the [paper](https://ieeexplore.ieee.org/abstract/document/8545493) for details.
