### ISSUE TITLE
create annotation for the custom image dataset 

### ISSUE THREAD

**Issue by sivaeinfo** [yangli18/hand_detection#17]
You have done great work. I want to use custom images, while using model. I would like to know how to create annotation for custom image dataset.

**Comment by yangli18** [comment]
@sivaeinfo You can refer to [the Oxford hand dataset](http://www.robots.ox.ac.uk/~vgg/data/hands/) to label upright or rotated bounding boxes for the hands present in your custom image dataset. There are quite a few annotation tools to try in [https://github.com/topics/annotations](https://github.com/topics/annotations).

**Comment by sivaeinfo** [comment]
@yangli18 Thank you for the information. I have tried default Oxford hand dataset. But While I was trying to run below command

siva@pop-os:~/hand1_ws/src/hand_detection/data/scripts$ **python3 create_trainval.py**

Even I have specified correct path in create_trainval.py. still I got following error. Please help me to sort out this issue. 



Traceback (most recent call last):
  File "create_trainval.py", line 99, in <module>
    createDataset(output_path, ann_path, img_path)
  File "create_trainval.py", line 35, in createDataset
    ann_list = os.listdir(ann_path)
 File "scripts/create_trainval.py", line 31, in createDataset
    env = lmdb.open(outputPath, map_size=1099511627776)
FileNotFoundError: [Errno 2] No such file or directory: 'hand1_ws/src/hand_detection/data/hand_dataset/training_dataset/training_data/annotations/'
siva@pop-os:~/hand1_ws/src/hand_detection/data/scripts$

**Comment by sivaeinfo** [comment]
@yangli18 I also facing the following
siva@pop-os:~/hand2_ws/hand_detection$ sh layers/src/make.sh
Compiling nms kernels by nvcc...
Traceback (most recent call last):
  File "build.py", line 3, in <module>
    from torch.utils.ffi import create_extension
  File "/home/siva/.local/lib/python3.8/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.

**Comment by sivaeinfo** [comment]
@yangli18 Did you use linux or windows - anaconda for the hand detection project?
I am using Ubuntu 20.04.

**Comment by yangli18** [comment]
@sivaeinfo These errors may be because the Oxford dataset is not ready yet (based on the error message). Make sure you have completed the preparation process. If any error occurs, you can manually execute each command in the Oxford_hand_dataset.sh to prepare the dataset.

> @yangli18 Thank you for the information. I have tried default Oxford hand dataset. But While I was trying to run below command
> 
> siva@pop-os:~/hand1_ws/src/hand_detection/data/scripts$ **python3 create_trainval.py**
> 
> Even I have specified correct path in create_trainval.py. still I got following error. Please help me to sort out this issue.
> 
> Traceback (most recent call last): File "create_trainval.py", line 99, in createDataset(output_path, ann_path, img_path) File "create_trainval.py", line 35, in createDataset ann_list = os.listdir(ann_path) File "scripts/create_trainval.py", line 31, in createDataset env = lmdb.open(outputPath, map_size=1099511627776) FileNotFoundError: [Errno 2] No such file or directory: 'hand1_ws/src/hand_detection/data/hand_dataset/training_dataset/training_data/annotations/' siva@pop-os:~/hand1_ws/src/hand_detection/data/scripts$

**Comment by yangli18** [comment]
> @yangli18 I also facing the following siva@pop-os:~/hand2_ws/hand_detection$ sh layers/src/make.sh Compiling nms kernels by nvcc... Traceback (most recent call last): File "build.py", line 3, in from torch.utils.ffi import create_extension File "/home/siva/.local/lib/python3.8/site-packages/torch/utils/ffi/**init**.py", line 1, in raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.") ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.

Make sure your PyTorch version is 0.3.0. If you want to use the newer PyTorch, you may
need to compile the NMS kernel with cpp extensions, since torch.utils.ffi is deprecated.

**Comment by sivaeinfo** [comment]
@yangli18 
I have rectified the previous error shown for the command Oxford_hand_dataset.sh. 
To install pytorch version 0.3.0, shall I use ubuntu 18.04. Now I am using Ubuntu 20.04. I tried cpp extension, again it shows few more error. Can you show me the way to rectify the error. If you have any documentation with more details to carry out his project. Please mail to sivaeinfo@gmail.com

**Comment by yangli18** [comment]
@sivaeinfo 
Both versions of Ubuntu should work. Regarding the use of cpp extension, you can refer to [https://pytorch.org/tutorials/advanced/cpp_extension.html](https://pytorch.org/tutorials/advanced/cpp_extension.html). You can also refer to this [paper](https://ieeexplore.ieee.org/abstract/document/8545493) for technical details of this project.

**Comment by sivaeinfo** [comment]
**I have found cpp extension in webpage. Shall I use. I have shown cpp_extension below. Do you have any cpp_extension for your build.py. I dont know how to change build.py to include cpp_extension**

#!/usr/bin/env python

import os
import sys

from setuptools import setup, find_packages

import build

this_file = os.path.dirname(__file__)
from torch.utils.cpp_extension import BuildExtension, CppExtension

setup(
    name="torchaudio",
    version="0.1",
    description="An audio package for PyTorch",
    url="https://github.com/pytorch/audio",
    author="Soumith Chintala, David Pollack, Sean Naren",
    author="Soumith Chintala, David Pollack, Sean Naren, Peter Goldsborough",
    author_email="soumith@pytorch.org",
    # Require cffi.
    install_requires=["cffi>=1.0.0"],
    setup_requires=["cffi>=1.0.0"],
    # Exclude the build files.
    packages=find_packages(exclude=["build"]),
    # Package where to put the extensions. Has to be a prefix of build.py.
    ext_package="",
    # Extensions to compile.
    cffi_modules=[
        os.path.join(this_file, "build.py:ffi")
    ext_modules=[
        CppExtension(
            '_torch_sox', ['torchaudio/torch_sox.cpp'], libraries=['sox']),
    ],
)
    cmdclass={'build_ext': BuildExtension})

**Comment by sivaeinfo** [comment]
@yangli18 Hi, I have tried. I am not able to create build.py for cpp_extension because I dont have much knowledge in these thing. I have python knowledge and basic CNN programming knowledge. 

If you tell me, what kind of Ubuntu OS version, python version and Cuda version that you have used to create this project, I will use the same version and other packages. Then I can eliminate these error. Or shall I use anaconda older version.

**Comment by yangli18** [comment]
@sivaeinfo 
I'm also not familiar with this cpp_extension. When implementing this project, I used PyTorch 0.3.0, Python 3.6.8, Ubuntu 16.04, Cuda 7.5. 
* The last two should be ok using higher versions, but it may require compiling PyTorch from source, if the corresponding PyTorch binaries (e.g., PyTorch 0.3.0 + Cuda 9.0) are not available from conda or pip.
* If you want to use the newer PyTorch, you may have to fix some incompatibilities (including cpp_textension or other API functions) due to PyTorch's updates.

**Comment by sivaeinfo** [comment]
I have cleared all the previous error and cleared import error to install torchvision. I just installed torchvision 0.1.6. 

When I run train.py, I had following error.
    
(proj1) sivabalakrishnanr@pop-os:~/hand_workspace/src/hand_detection$ python train.py 2>&1 | tee log/train.log
Loading base network...
Initializing weights...
Loading Dataset...
Training SSD_mobilenet ssd_new_mobilenet_FFA on Oxford hand dataset with multibox loss
Data augmentaion: v1
/home/sivabalakrishnanr/handenv/proj1/lib/python3.6/site-packages/torch/cuda/__init__.py:87: UserWarning: 
    Found GPU0 NVIDIA GeForce GTX 1050 Ti which requires CUDA_VERSION >= 8000 for
     optimal performance and fast startup time, but your PyTorch was compiled
     with CUDA_VERSION 7050. Please install the correct PyTorch binary
     using instructions from http://pytorch.org
    
  warnings.warn(error_str % (d, name, 8000, CUDA_VERSION))

**Comment by sivaeinfo** [comment]
I ran train.py, I am getting following result. Is it right? Is there any possibility to rectify these warning.

Training SSD_mobilenet ssd_new_mobilenet_FFA on Oxford hand dataset with multibox loss
Data augmentaion: v1
/home/sivabalakrishnanr/handenv/proj1/lib/python3.6/site-packages/torch/cuda/__init__.py:87: UserWarning: 
    Found GPU0 NVIDIA GeForce GTX 1050 Ti which requires CUDA_VERSION >= 8000 for
     optimal performance and fast startup time, but your PyTorch was compiled
     with CUDA_VERSION 7050. Please install the correct PyTorch binary
     using instructions from http://pytorch.org
    
  warnings.warn(error_str % (d, name, 8000, CUDA_VERSION))
Timer: 217.2945 sec.
iter 0 || lr: 0.001000  || loc_loss: 24.9140  || cls_loss: 12.6306  Saving state, iter: 0
Timer: 0.1974 sec.
iter 100 || lr: 0.001000  || loc_loss: 14.4188  || cls_loss: 3.3238  Timer: 0.1996 sec.
iter 200 || lr: 0.001000  || loc_loss: 12.9088  || cls_loss: 2.6630  /home/sivabalakrishnanr/handenv/proj1/lib/python3.6/site-packages/torch/autograd/_functions/tensor.py:447: UserWarning: mask is not broadcastable to self, but they have the same number of elements.  Falling back to deprecated pointwise behavior.
  return tensor.masked_fill_(mask, value)
/home/sivabalakrishnanr/hand_workspace/src/hand_detection/utils/augmentations.py:236: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  mode = random.choice(self.sample_options)
/home/sivabalakrishnanr/hand_workspace/src/hand_detection/utils/augmentations.py:236: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  mode = random.choice(self.sample_options)
/home/sivabalakrishnanr/hand_workspace/src/hand_detection/utils/augmentations.py:236: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  mode = random.choice(self.sample_options)
/home/sivabalakrishnanr/hand_workspace/src/hand_detection/utils/augmentations.py:236: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  mode = random.choice(self.sample_options)
/home/sivabalakrishnanr/hand_workspace/src/hand_detection/utils/augmentations.py:236: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  mode = random.choice(self.sample_options)
Timer: 0.1958 sec.
iter 300 || lr: 0.001000  || loc_loss: 9.6381  || cls_loss: 2.4862  Timer: 0.1967 sec.
iter 400 || lr: 0.001000  || loc_loss: 9.5413  || cls_loss: 2.4115  Timer: 0.2045 sec.
iter 500 || lr: 0.001000  || loc_loss: 8.4384  || cls_loss: 2.3480  /home/sivabalakrishnanr/hand_workspace/src/hand_detection/utils/augmentations.py:236: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  mode = random.choice(self.sample_options)
/home/sivabalakrishnanr/hand_workspace/src/hand_detection/utils/augmentations.py:236: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  mode = random.choice(self.sample_options)
/home/sivabalakrishnanr/hand_workspace/src/hand_detection/utils/augmentations.py:236: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  mode = random.choice(self.sample_options)
/home/sivabalakrishnanr/hand_workspace/src/hand_detection/utils/augmentations.py:236: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  mode = random.choice(self.sample_options)
/home/sivabalakrishnanr/hand_workspace/src/hand_detection/utils/augmentations.py:236: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  mode = random.choice(self.sample_options)
Timer: 0.1950 sec.
iter 600 || lr: 0.001000  || loc_loss: 8.4205  || cls_loss: 2.2814  Timer: 0.2097 sec.
iter 700 || lr: 0.001000  || loc_loss: 12.0567  || cls_loss: 2.3542  /home/sivabalakrishnanr/hand_workspace/src/hand_detection/utils/augmentations.py:236: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  mode = random.choice(self.sample_options)
/home/sivabalakrishnanr/hand_workspace/src/hand_detection/utils/augmentations.py:236: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  mode = random.choice(self.sample_options)
/home/sivabalakrishnanr/hand_workspace/src/hand_detection/utils/augmentations.py:236: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  mode = random.choice(self.sample_options)
/home/sivabalakrishnanr/hand_workspace/src/hand_detection/utils/augmentations.py:236: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  mode = random.choice(self.sample_options)
/home/sivabalakrishnanr/hand_workspace/src/hand_detection/utils/augmentations.py:236: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  mode = random.choice(self.sample_options)
