### ISSUE TITLE
I ssue with error: nms_kernel.cu: No such file or directory

### ISSUE THREAD

**Issue by Azazel17** [yangli18/hand_detection#2]
Basically that my problem i have already fixewd all my previous issues but now i get this error in the  make.sh execution. 

Any help would be very appreciated sir

Thanks in advance 

My OS is Windows 10 by the way

**Comment by yangli18** [comment]
@Azazel17  My OS is Ubuntu 16.04 and the command `sh layers/src/make.sh` works properly here. I haven't tested it on Windosw 10. The script `nms_kernel.cu` locates in `layers/src/cuda/`. You should check that and try to figure out why this script was not found.

**Comment by trungpham2606** [comment]
@Azazel17  Were you able to run this repo in your PC yet ? Can you tell me which version of pytorch you are using ?
