### ISSUE TITLE
Issue with torch.utils.ffi

### ISSUE THREAD

**Issue by Azazel17** [yangli18/hand_detection#3]
So, now i'm on Ubuntu 16.04 everything appears to be fine until build.py i got this error : 

Traceback (most recent call last):
  File "build.py", line 3, in <module>
    from torch.utils.ffi import create_extension
  File "/home/the-taco-coder/.local/lib/python3.5/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.

Any help would be really appreciated. 

Thanks iin advance for the awesome work

**Comment by yangli18** [comment]
@Azazel17  I recommend using PyTorch 0.3.0. The `torch.utils.ffi` is deprecated in the latest versions of PyTorch. You can refer to this [project](https://github.com/jwyang/faster-rcnn.pytorch/tree/pytorch-1.0) to use cpp extensions for the NMS code.
