### ISSUE TITLE
Orientation Estimation 

### ISSUE THREAD

**Issue by trungpham2606** [yangli18/hand_detection#4]
@yangli18  What a great work. I just saw your work few days ago, read your paper but when looking into your codes, I cant see where Projection loss and Wrist loss are ?

**Comment by yangli18** [comment]
@trungpham2606 
As both of them are defined as the smooth L1 loss, they are calculated along with the location loss L<sub>loc</sub> in [multibox_loss.py](https://github.com/yangli18/hand_detection/blob/master/layers/modules/multibox_loss.py).

**Comment by trungpham2606** [comment]
@yangli18 oh, thank you. In addition, can you give me information about the loc_loss and cls_loss after finishing your training session. It seems that your log file doesn't contain the final results.

**Comment by yangli18** [comment]
@trungpham2606 
I just updated the training log. It is corresponding to the trained model in `weights` dir.

**Comment by trungpham2606** [comment]
@yangli18 oh I see it. Thank you for your prompt response. I had tried your network with my own dataset and the results are immensely good !

**Comment by yangli18** [comment]
@trungpham2606 I'm glad it helped! :smile:

**Comment by trungpham2606** [comment]
@yangli18 Can you tell me how much time the model needs for showing results on 1 image ( prediction time + display time). In my PC, the amount of time for 1 image is approximately 1sec ( I was using pure Python nms).
Thank in advance.

**Comment by yangli18** [comment]
@trungpham2606 
We tested the average detection time (including NMS) on the Oxford hand dataset, and it's about **7 ms/image** using Titan X (Maxwell). We didn't count the display time and you should test it yourself on your platform. The NMS written in c/cuda is also provided and it's much faster.

**Comment by trungpham2606** [comment]
@yangli18 Yeah, I also guessed that it took most time in display part while I was using pure Python nms ( i cant install nms c/cuda built on windows 10, I will try cython version). 
Thanks so much for helping me ^^.

**Comment by yangli18** [comment]
@trungpham2606 My pleasure! Thanks for your interest.
