### ISSUE TITLE
KeyError: 'module name can\'t contain "."'

### ISSUE THREAD

**Issue by Vincent-2017** [yangli18/hand_detection#5]
Hello, I have problem during running the `python3 eval.py --trained_model weights/ssd_new_mobilenet_FFA.pth --version ssd_new_mobilenet_FFA`
The error message is  ` KeyError: 'module name can\'t contain "."'`
How to fix it?

**Comment by yangli18** [comment]
@Vincent-2017 
Hi, this is because the latest pytorch doesn't allow `"."` in module keys. You can rename the module keys or use pytorch 0.3.0.

**Comment by Vincent-2017** [comment]
Thank you, I have fixed the problem.
what is the difference between the three versions?
- `if args.version == 'ssd_new_mobilenet_FFA':
-     from models.ssd_new_mobilenet_FFA import build_ssd
- elif args.version == 'ssd_new_mobilenet':
-     from models.ssd_new_mobilenet import build_ssd
- elif args.version == 'ssd_mobilenet':
-     from models.ssd_mobilenet import build_ssd`

**Comment by yangli18** [comment]
The original mobilenet is used as the backbone in `ssd_mobilenet`. The `ssd_new_mobilenet` modifies its structure to make the 38×38 feature map deeper. The `ssd_new_mobilenet_FFA` adds a feature fusion structure like FPN. For details, you can refer to this [paper](https://ieeexplore.ieee.org/abstract/document/8545493).

**Comment by Vincent-2017** [comment]
I would read the paper, thank you.
When I test the model with the images you give, I find that some scores are -inf and there are many hands not  detected in some cases. In fact, these hands are very obvious in the image.

**Comment by yangli18** [comment]
@Vincent-2017 
Could you tell me the images you tested and the detection results? It's a bit strange to get -inf scores.

**Comment by Vincent-2017** [comment]
@yangli18 
I test the images again and the model output scores without -inf in this case.

**Comment by yangli18** [comment]
@Vincent-2017 
How is the detection performance? Are there still many hands not detected?

**Comment by Vincent-2017** [comment]
@yangli18 
If a reasonable threshold is set, most of the hands can be detected, but it is inevitable that there are misidentifications and omissions.

**Comment by yangli18** [comment]
@Vincent-2017 
Yes, it's still hard for current detection algorithms to avoid this.
