### ISSUE TITLE
 'module name can\'t contain "."'

### ISSUE THREAD

**Issue by ZHEQIUSHUI** [yangli18/hand_detection#8]
what is version with pytorch to run demo?i have installde 1.2.but when i run dem,bui it is wrong.

error in mobilenet_v1_base "end_point_base"

**Comment by yangli18** [comment]
@ZHEQIUSHUI 
Hi, this project is currently compatible with pytorch 0.3.0. Some modifications to the project are required to support pytorch 1.2.

**Comment by cansik** [comment]
What version of torchvision did you use?
