### ISSUE TITLE
Got import error when running evaluation

### ISSUE THREAD

**Issue by jtao151617** [yangli18/hand_detection#9]
python eval.py --trained_model weights/ssd_new_mobilenet_FFA.pth --version ssd_new_mobilenet_FFA --cuda False 

got error:

ImportError: /home/vr/handOrientation/hand_detection/layers/_ext/nms/_nms.so: undefined symbol: __cudaRegisterFatBinaryEnd

**Comment by yangli18** [comment]
@jtao151617 
Hi, you can refer to [this](https://github.com/open-mmlab/mmdetection/issues/385).

**Comment by jtao151617** [comment]
Yes. It was the version compatibility. It works with Cuda 9 Pytorch 0.3.0 and TorchVision 0.2.0
